banner:
  enable: true
  title:
    - NA
    - GI
    - SB
    - Blog
  border: true
  cloud:
    enable: true
    color: white
  go_down:
    enable: true
    icon: ri:arrow-down-s-line
#é¼ æ ‡æ ·å¼
cursor:
  enable: true
  default: https://cdn.yunyoujun.cn/css/md-cursors/pointer.cur
  pointer: https://cdn.yunyoujun.cn/css/md-cursors/link.cur
  text: https://cdn.yunyoujun.cn/css/md-cursors/text.cur
avatar:
  enable: true
  url: nagisb.png
  rounded: true
  opacity: 1
  mickey_mouse: false
  status:
    enable: true
    emoji: ğŸ˜­
    message: ä¸æƒ³ä¸Šå­¦
pages:
  - name: æˆ‘çš„å°ä¼™ä¼´ä»¬
    url: /links/
    icon: ri:genderless-line
    color: dodgerblue
social:
  - name: ç½‘æ˜“äº‘éŸ³ä¹
    link: https://music.163.com/#/user/home?id=1682645831
    icon: ri:netease-cloud-music-line
    color: '#C10D0C'
post_meta:
  item_text: false
  created_at: true
  updated_at: true
  categories: true
  tags: true
wordcloud:
  enable: true
footer:
  icon:
    name: ri:cloud-line
    title: 404NOT FOUNT
    url: /404.html
  powered:
    enable: false
  live_time:
    enable: true
    prefix: æœ¬åšå®¢å·²èŒèŒå“’åœ°è¿è¡Œ
    suffix: (â—'â—¡'â—)
    start_time: '2020-07-19T22:21:00'
menu:
  home:
    title: é¦–é¡µ
    path: /
    icon: ri:home-4-line
  list:
    - type: archives
      path: /archives/
      icon: ri:archive-line
    - type: categories
      path: /categories/
      icon: ri:folder-2-line
    - type: tags
      path: /tags/
      icon: ri:price-tag-3-line
    # - path: https://www.yunyoujun.cn
    #   icon: ri:cloud-line
    #   count: ä½ çŒœ
  custom:
    title: æ–‡ä»¶
    path: https://yun.yunyoujun.cn
    icon: ri:folder-2-line










